apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia
spec:
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 3
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
        - image: edwin/kubia:v3
          name: nodejs
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            periodSeconds: 1
            httpGet:
              path: /
              port: 8080
  selector:
    matchLabels:
      app: kubia
