apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kubia
  name: kubia-manual
spec:
  containers:
    - image: edwin/kubia:v1
      imagePullPolicy: IfNotPresent
      name: kubia
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
